### ISSUE TITLE
json: cannot unmarshal string into Go struct field PhysicalDrive.Controllers.Response Data.PD LIST.DG of type int

### ISSUE THREAD

**Issue by panboo0106** [bwcarp/storcli-collector#2]
### Describe:
I hava SSD in JBOD. When I executed the program, the following error occurred.
![image](https://github.com/blakehartshorn/storcli-collector/assets/57588266/f30bd523-edec-4716-8009-3e0bc898d441)

I don't know where things went wrong. So I just I modified the code to fit my scenario.

**Comment by panboo0106** [comment]
![image](https://github.com/blakehartshorn/storcli-collector/assets/57588266/49e788cb-ceb3-416e-b77e-47deab7b61d6)

**Comment by bwcarp** [comment]
That's curious. Is this with the megaraid or the mpt3sas driver? Would you feel comfortable with sharing the full json output with me so I could test locally?

**Comment by panboo0106** [comment]
Sorry for the late reply.

lspci -k | grep RAID
3b:00.0 RAID bus controller: Broadcom / LSI MegaRAID Tri-Mode SAS3508 (rev 01)
[storclilog.log](https://github.com/blakehartshorn/storcli-collector/files/12398220/storclilog.log)

**Comment by panboo0106** [comment]
Any updates?

**Comment by bwcarp** [comment]
Sorry, have been pretty distant from this project for a while.

I'm going to fix this within the next week. I found the problem.
